### ISSUE TITLE
复杂参数的查询

### ISSUE THREAD

**Issue by yfhuang521** [MountCloud/graphql-client#10]
@MountCloud
你好请部复杂参数如何查询？
{
  pair(id: 50, block:{number:100}) {
    id
  }
}
这个 block:{number:100}这块参数要怎么传递，多谢

**Comment by MountCloud** [comment]
> @MountCloud
> 你好请部复杂参数如何查询？
> {
> pair(id: 50, block:{number:100}) {
> id
> }
> }
> 这个 block:{number:100}这块参数要怎么传递，多谢


Request可以这样构造

`

        //声明block参数，这个可以是map可以是自己的类，有个number属性类型是int或者integer或者long就行
        Map<String,Object> blockParam = new HashMap<>();
        blockParam.put("number",100);

        GraphqlRequest request = new DefaultGraphqlQuery("pair");
        //id参数跟block参数一起添加
        request.addParameter("id",50)
                .addObjectParameter("block",blockParam);
        //也可以单独户添加block参数，ObjectParameter可以是map可以是自己的实体类。
        request.getRequestParameter().addObjectParameter("block",blockParam);
        //result值返回一个id
        request.addResultAttributes("id");

`

**Comment by yfhuang521** [comment]
> > @MountCloud
> > 你好请部复杂参数如何查询？
> > {
> > pair(id: 50, block:{number:100}) {
> > id
> > }
> > }
> > 这个 block:{number:100}这块参数要怎么传递，多谢
> 
> Request可以这样构造
> 
> `
> 
> ```
>     //声明block参数，这个可以是map可以是自己的类，有个number属性类型是int或者integer或者long就行
>     Map<String,Object> blockParam = new HashMap<>();
>     blockParam.put("number",100);
> 
>     GraphqlRequest request = new DefaultGraphqlQuery("pair");
>     //id参数跟block参数一起添加
>     request.addParameter("id",50)
>             .addObjectParameter("block",blockParam);
>     //也可以单独户添加block参数，ObjectParameter可以是map可以是自己的实体类。
>     request.getRequestParameter().addObjectParameter("block",blockParam);
>     //result值返回一个id
>     request.addResultAttributes("id");
> ```
> 
> `
加.addObjectParameter("block", blockMap)这段就查询不了
![image](https://user-images.githubusercontent.com/21332031/97949867-ed345e00-1dcf-11eb-8fd3-3c743ac2650a.png)
![image](https://user-images.githubusercontent.com/21332031/97949908-0c32f000-1dd0-11eb-8237-9b40473e8fbd.png)
这个是代码
@Test
	public void pairInfo() {
		
		try {
			String url = "https://api.thegraph.com/subgraphs/name/therealsakeswap/sakeswap-subgraph-v2";
			GraphqlClient graphqlClient = GraphqlClient.buildGraphqlClient(url);
	        
			// block
			Map<String, Object> blockMap = new HashMap<String, Object>();
			blockMap.put("number", 11149005);
			
			GraphqlQuery query = new DefaultGraphqlQuery("pair");
			query.addParameter("id", "0xca3d6a94759cb675f0ac10a76fc0da6ee6bf6e7b").addObjectParameter("block", blockMap);
			query.addResultAttributes("id");
	        System.out.println(query.toString());
	        
			GraphqlResponse response = graphqlClient.doQuery(query);
			System.out.println(response.getData().toString());
		} catch (Exception e) {
			e.printStackTrace();
		}
	    	
	}

**Comment by yfhuang521** [comment]
@MountCloud  能帮我确认下吗？
加.addObjectParameter("block", blockMap)这段就查询不了
![image](https://user-images.githubusercontent.com/21332031/97949867-ed345e00-1dcf-11eb-8fd3-3c743ac2650a.png)
![image](https://user-images.githubusercontent.com/21332031/97949908-0c32f000-1dd0-11eb-8237-9b40473e8fbd.png)
这个是代码
@Test
	public void pairInfo() {
		
		try {
			String url = "https://api.thegraph.com/subgraphs/name/therealsakeswap/sakeswap-subgraph-v2";
			GraphqlClient graphqlClient = GraphqlClient.buildGraphqlClient(url);
	        
			// block
			Map<String, Object> blockMap = new HashMap<String, Object>();
			blockMap.put("number", 11149005);
			
			GraphqlQuery query = new DefaultGraphqlQuery("pair");
			query.addParameter("id", "0xca3d6a94759cb675f0ac10a76fc0da6ee6bf6e7b").addObjectParameter("block", blockMap);
			query.addResultAttributes("id");
	        System.out.println(query.toString());
	        
			GraphqlResponse response = graphqlClient.doQuery(query);
			System.out.println(response.getData().toString());
		} catch (Exception e) {
			e.printStackTrace();
		}
	    	
	}

**Comment by yfhuang521** [comment]
@MountCloud 
![image](https://user-images.githubusercontent.com/21332031/97953402-553c7180-1ddb-11eb-86e7-ad13872b2788.png)
![image](https://user-images.githubusercontent.com/21332031/97953406-5bcae900-1ddb-11eb-8e5f-971423f026ae.png)
这是在MountCloud/graphql-client项目源码里面测试的，可以得到结果。但是引入 jar到项目就调用不了

**Comment by yfhuang521** [comment]
@MountCloud 
问题已解决，缺少jar包：jackson-datatype-jdk8
感谢！！！！！
