### ISSUE TITLE
where 条件参数怎么传

### ISSUE THREAD

**Issue by yueliang011** [MountCloud/graphql-client#19]

**Comment by MountCloud** [comment]
对应的graphql语句是什么呢

**Comment by yueliang011** [comment]
{
 poolHourDatas(where:{pool:"0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"},
  first:100
  orderBy: periodStartUnix,orderDirection: desc){
  id
  periodStartUnix
  pool{
    id
    token0{
      id
      symbol
      derivedETH
    }
    token1{
      id
      symbol
      derivedETH
    }
  }
    liquidity
    sqrtPrice
    token0Price
    token1Price
    tick
    feeGrowthGlobal0X128
    feeGrowthGlobal1X128
    tvlUSD
    volumeToken0
    volumeToken1
    volumeUSD
    txCount
    open
    high
    low
    close
}
}

**Comment by MountCloud** [comment]
参考README.md的“如何实现一个复杂请求”

**Comment by yueliang011** [comment]
返回结果为:{"errors":[{"message":"Not supported: Mutations are not supported"}]}
 private static GraphqlMutation buildPoolHourData1() {
        
        GraphqlMutation mutation = new DefaultGraphqlMutation("poolHourDatas");
        mutation.addResultAttributes("id", "periodStartUnix", "liquidity", "sqrtPrice", "token0Price",
                "token1Price", "tick", "feeGrowthGlobal0X128", "feeGrowthGlobal1X128", "tvlUSD",
                "volumeToken0", "volumeToken1", "volumeUSD", "feesUSD", "txCount", "open", "high", "low", "close");
        ResultAttributtes pool = new ResultAttributtes("pool");
        pool.addResultAttributes("id");
        mutation.addResultAttributes(pool);
        // 入参
        Pool build = Pool.builder().pool("0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640").build();
        mutation.getRequestParameter().addParameter("orderDirection", "desc")
                .addParameter("orderBy", "periodStartUnix")
                .addObjectParameter("pool", build);
        
        return mutation;
    }

**Comment by MountCloud** [comment]
这个你得看你的是Mutation还是Query

**Comment by MountCloud** [comment]
而且你这个代码我看跟语句也没对应上，少了层where

**Comment by yueliang011** [comment]
这个where怎么加啊

**Comment by yueliang011** [comment]
private static GraphqlQuery buildPoolHourData() {
        String queryMethodName1 = "poolHourDatas";
        
        GraphqlQuery query = new DefaultGraphqlQuery(queryMethodName1);
        query.addResultAttributes("id", "periodStartUnix", "liquidity", "sqrtPrice", "token0Price",
                "token1Price", "tick", "feeGrowthGlobal0X128", "feeGrowthGlobal1X128", "tvlUSD",
                "volumeToken0", "volumeToken1", "volumeUSD", "feesUSD", "txCount", "open", "high", "low", "close");
        ResultAttributtes pool = new ResultAttributtes("pool");
        pool.addResultAttributes("id");
        query.addResultAttributes(pool);
        Pool build = Pool.builder().pool("0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640").build();
        query.addParameter("orderBy", "periodStartUnix");
        query.addParameter("orderDirection", "desc");
        query.getRequestParameter().addObjectParameter("where",build);
        return query;
        
    }

**Comment by MountCloud** [comment]
where作为一个对象，where属性就是你语句里的属性，我记得是这样哦，这个项目好久没看过了，query.addParameter("where", where)；

**Comment by MountCloud** [comment]
mutation和query可以直接.toString()可以打印看看，跟语句能不能对应上

**Comment by yueliang011** [comment]
感谢，老铁我弄出来了

**Comment by MountCloud** [comment]
客气了~star求一个
